name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=16384

    steps:
      - name: Debug Environment Variables
        run: env
