name: Display Secret Value (Securely)

on:
  push:
    branches:
      - main

jobs:
  show-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Show secret variable
        env:
          MY_SECRET: ${{ secrets.APP_KEY_DEV }}
        run: |
          echo "A secret foi configurada com sucesso!"
          echo "Comprimento da variável secreta: ${#MY_SECRET} caracteres"
